### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by kirtiesl** [g1eb/angular2-calendar-heatmap#2] opened 2017-05-30 05:18 UTC
Hello,
I get below error after including this statement import { CalendarHeatmap } from 'angular2-calendar-heatmap';

ERROR in Error encountered resolving symbol values statically. Could not resolve
 angular2-calendar-heatmap relative to E:/angmarc/src/app/app.module.ts., resolv
ing symbol AppModule in E:/angmarc/src/app/app.module.ts, resolving symbol AppMo
dule in E:/angmarc/src/app/app.module.ts

Please suggest asap. Its urgent

**Comment by g1eb** [comment] 2017-05-30 07:24
Hi there! What does your `systemjs.config.js` file look like? That's typically the place you tell your app where to look for the `angular2-calendar-heatmap` component. ([example](https://github.com/g1eb/angular2-calendar-heatmap/blob/master/systemjs.config.js#L53))

**Comment by kirtiesl** [comment] 2017-05-30 08:47
We do not use systemjs.config.js in our project. Please suggest any other solution

**Comment by g1eb** [comment] 2017-05-30 08:51
Hm okay, what do you use to load modules into your app?

Are the modules loaded into a bundle with webpack or do you reference source files directly in your index.html? I need to know a little bit more about your setup.

**Comment by kirtiesl** [comment] 2017-05-30 08:52
We use webpack

**Comment by kirtiesl** [comment] 2017-05-30 08:55
Angular version : 2.4.3
angular-cli: 1.0.0-beta.28.3
node: 6.10.3
os: win32 x64

**Comment by kirtiesl** [comment] 2017-05-30 09:32
Any updates. Its urgent!!

**Comment by g1eb** [comment] 2017-05-30 10:11
Yes, I'm looking into this trying to reproduce the issue with a clean angular2 project :)

Was the project created with angular-cli? And if so, did you run the `ng eject` command yet? You should not have to but it's good to know if you did.

I think the problem might be in the way the module is exported, I need more time to investigate this though, when is your deadline?

**Comment by kirtiesl** [comment] 2017-05-30 10:39
Yes tried the ng eject command but no luck.
Is angular2-calendar-heatmap compatible with angular 4? I have to get it done by today

**Comment by g1eb** [comment] 2017-05-30 13:48
Same here, I've tried a bunch of stuff to export the package and I've got to the point that it recognizes the library but is missing `moment` and `d3` dependencies.

I'll let you know when I get it to work although I doubt it will happen today.

**Comment by kirtiesl** [comment] 2017-05-31 03:48
Thanks. 
May I know when it will be fixed and ready to use.

**Comment by g1eb** [comment] 2017-06-06 13:08
Hi there! As it turns out - this was a somewhat larger fix than anticipated, mostly due to the entirely new [Angular Package Format](https://goo.gl/AMOU5G), this is a requirement for AoT compilation methods. Developers are now required to publish type definitions and metadata as most new tools, such as `angular-cli`, work with that.

I've updated build process and calendar-heatmap now comes in two flavours:
1. Universal Module Definition (UMD bundle)
2. Flat ES Module (FESM)

Install procedures remain the same, let me know if this works for you :)

v0.1.0

**Comment by Foxandxss** [comment] 2017-06-07 08:28
it should be fine.

**Comment by g1eb** [comment] 2017-06-08 00:13
Thanks for double checking! Yeah, it should work now, closing this issue :)

**Comment by kirtiesl** [comment] 2017-06-08 04:23
Sorry but it's still not working for me

**Comment by g1eb** [comment] 2017-06-08 06:48
No problem, what is the error that you get?

**Comment by Foxandxss** [comment] 2017-06-08 09:25
I'll triple check then

**Comment by g1eb** [comment] 2017-06-08 10:07
I've tested this by creating a fresh project using `@angular/cli` and installing `angular2-calendar-heatmap` with npm. I copied the template from the demo project in `app/app.component.ts` and that worked just fine.

The only issue might be importing `moment` and `d3` dependencies. For testing purposes I include inline refs to cdn inside of `src/index.html` (I  am not sure if that's something that can be set in this library or on the actual project)

**Comment by g1eb** [comment] 2017-06-27 16:19
Hi @kirtiesl, it's been a while, just checking in to see if you got this to work.

Let me know if there are still any issues with importing :)

**Comment by kirtiesl** [comment] 2017-06-28 09:06
Thanks g1eb for update.
But i still get this error
ERROR ReferenceError: d3 is not defined
    at CalendarHeatmap.webpackJsonp../node_modules/angular2-calendar-heatmap/dist/calendar-heatmap.js.CalendarHeatmap.ngAfterViewInit (calendar-heatmap.js:43)
    at callProviderLifecycles (core.es5.js:11052)
    at callElementProvidersLifecycles (core.es5.js:11027)
    at callLifecycleHooksChildrenFirst (core.es5.js:11011)
    at checkAndUpdateView (core.es5.js:12033)
    at callViewAction (core.es5.js:12340)
    at execComponentViewsAction (core.es5.js:12286)
    at checkAndUpdateView (core.es5.js:12031)
    at callViewAction (core.es5.js:12340)
    at execEmbeddedViewsAction (core.es5.js:12312)
    at checkAndUpdateView (core.es5.js:12026)
    at callViewAction (core.es5.js:12340)
    at execEmbeddedViewsAction (core.es5.js:12312)
    at checkAndUpdateView (core.es5.js:12026)
    at callViewAction (core.es5.js:12340)

Is it compatible with angular 4

**Comment by g1eb** [comment] 2017-06-28 09:23
Yeah, the problem here is that the library depends on `d3` and `moment` libs and they are not imported. In my [example](https://github.com/g1eb/angular2-calendar-heatmap/blob/master/index.html) I've used cdn to import them in html, like so:

```
    <script src="https://unpkg.com/moment@2.12.0/min/moment.min.js" charset="utf-8"></script>
    <script src="https://unpkg.com/d3@3.5.16/d3.min.js" charset="utf-8"></script>
```

Could you try that and let me know if that works for you? Additionally you can get `[d3](https://www.npmjs.com/package/d3)` and `[moment](https://www.npmjs.com/package/moment)` from npm and include them in your project that way.

@Foxandxss i had these two libs listed as `peerDependencies` in my [package.json](https://github.com/g1eb/angular2-calendar-heatmap/blob/master/package.json), shouldn't that just be regular dependencies with a specific version number specified?

**Comment by kirtiesl** [comment] 2017-06-28 09:28
I have already installed d3 and moment dependencies.

**Comment by g1eb** [comment] 2017-07-06 15:57
Hi, I looked into this to see if I can get the calendar heatmap to work with `d3` and `moment` js installed through npm instead of using a cdn.

Following [this guide](https://github.com/angular/angular-cli/wiki/stories-global-lib) if you install `d3@3.5.1` and `moment@2.18.1` using npm or yarn, you can add them to the scripts section of the  `.angular-cli.json` file, like this:

```
"scripts": [
  "../node_modules/moment/moment.js",
  "../node_modules/d3/d3.min.js"
],
```

This should allow you to declare and use both `d3` and `moment` libraries and subsequently calendar heatmap will also be able to use them. Could you please try that and let me know if you run into any more errors? :)

**Comment by g1eb** [comment] 2017-07-14 10:07
Hi @kirtiesl, were you able to fix this using the method described in my previous message?

**Comment by kirtiesl** [comment] 2017-10-10 09:03
Yes. Thanks for the help :)

**Closed** 2017-10-10 09:06 UTC
