### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jchapelle** [g1eb/angular2-calendar-heatmap#18] opened 2019-10-30 12:22 UTC
1. it possible to only display date range (e.g. last 6 months). If we're currently in january, the whole current year is displayed with 11 empty months ...
2. Is it possible to customize more in deep the colors ? I would like to avoid to display transparent dot

**Comment by g1eb** [comment] 2020-05-05 20:35
Hi! Apologies for the delayed reply, these are good features but not currently supported.
Unfortunately, number 1 was implemented like this by design - we needed a year based calendar.
Regarding number 2, you could clone/fork the project and change the colors fairly easily.

Let me know if you need help changing either one of the points above, closing for now.

**Closed by g1eb** 2020-05-05 20:35 UTC
